[env:matouch_s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
; Enables detailed boot logs to see WHY PSRAM might fail
monitor_filters = esp32_exception_decoder

build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=1  ; This helps diagnostic logs show up in Serial

; Crucial: qio_qspi means Quad Flash + Quad PSRAM (Standard for R2)
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.prsam_type = qio ; Some pio versions prefer this key
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

lib_deps =
    lovyan03/LovyanGFX @ ^1.1.16
    tzapu/WiFiManager @ ^2.0.17
    arduino-libraries/NTPClient @ ^3.2.1
    WiFi
    WiFiUdp